"""Add description to ConfigurationVersion

Revision ID: 38de568b5e31
Revises: 9ccf07ea36dd
Create Date: 2024-09-16 14:43:46.374413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38de568b5e31'
down_revision = '9ccf07ea36dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration_versions', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
