"""2nd  migration

Revision ID: 9ccf07ea36dd
Revises: 8a2d0abece60
Create Date: 2024-09-15 21:16:37.219346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ccf07ea36dd'
down_revision = '8a2d0abece60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration_versions')
    # ### end Alembic commands ###
